### ISSUE TITLE
npm start does not work until tsconfig.json changed (Windows)

### ISSUE THREAD

**Issue by kahenkel** [jmcooper/ng2-fundamentals#3] opened 2017-03-11 06:26 UTC
I couldn't get npm start to work on Windows after cloning the repo. The errors were as follows:
```
KHenkelmann@KHenkelmann-NB MINGW64 /c/dev/ng2-fundamentals (master)
$ npm start

> ng2-fundamentals-demo@1.0.0 start C:\dev\ng2-fundamentals
> tsc && concurrently "npm run tsc:w" "npm run server"

node_modules/@types/core-js/index.d.ts(47,36): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/core-js/index.d.ts(350,48): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(351,52): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(352,34): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(353,34): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(354,34): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(355,61): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(356,60): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(357,65): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(357,97): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(358,60): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(359,58): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(360,59): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(361,58): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(362,61): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(362,117): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(363,42): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(365,81): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(366,78): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(367,76): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(368,73): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(431,6): error TS2304: Cannot find name 'Symbol'.
node_modules/@types/core-js/index.d.ts(456,39): error TS2304: Cannot find name 'Promise'.
node_modules/@types/core-js/index.d.ts(464,59): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(465,59): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(467,48): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(468,69): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(472,40): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(474,48): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(494,55): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(495,45): error TS2304: Cannot find name 'PropertyKey'.
node_modules/@types/core-js/index.d.ts(511,46): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/core-js/index.d.ts(512,43): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/core-js/index.d.ts(627,18): error TS2304: Cannot find name 'PromiseConstructor'.
node_modules/@types/core-js/index.d.ts(642,32): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/core-js/index.d.ts(646,39): error TS2304: Cannot find name 'Iterable'.
node_modules/@types/core-js/index.d.ts(646,53): error TS2304: Cannot find name 'Iterator'.
node_modules/@types/core-js/index.d.ts(657,35): error TS2304: Cannot find name 'Promise'.
node_modules/@types/core-js/index.d.ts(1280,34): error TS2339: Property 'for' does not exist on type 'SymbolConstructor'.
(more)...
```

After doing some digging, I changed this line in the tsconfig.json from
```
"typeRoots": [
      "./node_modules/@types/"
    ]
```
to
```
"typeRoots": [
      "../node_modules/@types/"
    ]
```
After this change, npm start worked as expected.

**Comment by jamesbrittan** [comment] 2017-03-11 14:52
Experiencing the same issue on a Mac (Sierra). Your fix worked for me - thanks!

**Comment by jamesbrittan** [comment] 2017-03-12 15:32
Actually it seems like that was only a temporary fix. Broken again now.

**Comment by CybrZr00** [comment] 2017-03-13 09:42
Same problem on windows

**Comment by rickdana** [comment] 2017-03-13 20:44
Same issue !!

**Comment by MoAli2016** [comment] 2017-03-13 23:53
experiencing the same issue on mac sierra, fixed using kahenkel solution

**Comment by ksextontech** [comment] 2017-03-14 00:30
I had this same issue. It was fixed with kahenkel's suggestion.

**Comment by dominikjeske** [comment] 2017-03-15 08:06
For me fix was working but only for clean solution - after making first sample it fails again. The funny thing is that while doing changes on started server everything is working (while there are arror in console when compiling ts). After stop and start again I have this erros:

node_modules/@angular/common/src/directives/ng_class.d.ts(46,34): error TS2304: Cannot find name 'Set'.
node_modules/@angular/common/src/pipes/async_pipe.d.ts(44,38): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(369,30): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(415,30): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(416,20): error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(417,15): error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(418,246): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/directive_normalizer.d.ts(38,72): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/directive_normalizer.d.ts(40,74): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/metadata_resolver.d.ts(62,18): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/offline_compiler.d.ts(18,32): error TS2304: Cannot find name 'Map'.
node_modules/@angular/compiler/src/offline_compiler.d.ts(32,87): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/offline_compiler.d.ts(49,9): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/output/output_ast.d.ts(427,63): error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/resource_loader.d.ts(13,23): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/runtime_compiler.d.ts(44,49): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/runtime_compiler.d.ts(46,65): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/util.d.ts(26,18): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/util.d.ts(27,46): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_init.d.ts(16,18): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(106,67): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(122,101): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(148,67): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(150,101): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(28,16): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(88,123): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(88,165): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/lang.d.ts(13,17): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/linker/compiler.d.ts(53,49): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/compiler.d.ts(61,65): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/ng_module_factory_loader.d.ts(14,34): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.d.ts(28,25): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/util/lang.d.ts(8,53): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/platform-browser-dynamic/src/resource_loader/resource_loader_impl.d.ts(10,23): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/platform-browser/src/browser/browser_adapter.d.ts(79,33): error TS2304: Cannot find name 'Map'.
node_modules/@angular/platform-browser/src/dom/dom_adapter.d.ts(97,42): error TS2304: Cannot find name 'Map'.
node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts(22,37): error TS2304: Cannot find name 'Map'.
node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.

**Comment by dominikjeske** [comment] 2017-03-15 09:17
ok I have fixed this with setting target es to version 6 in tsconfig.json 

"target": "es6"

**Comment by LRizoJr** [comment] 2017-03-16 02:32
I have the same issue on my new laptop and it was also "fixed" by targeting es6. For some reason this is not an issue on my previous laptop or my desktop. It looks to be a versioning issue with TypeScript (there are certain libraries which angular2 uses which are not defined as part of es5 and these "typings" are supposed to be declared/installed separately, at least this is what Google says).

**Comment by joeeames** [comment] 2017-03-16 08:32
The problem is the latest revision of @types/core-js. 0.9.37 is the latest version, and that's what's broken. Maybe it's an incompatibility with the version of TypeScript we're using, maybe it's an incompatibility with core-js itself. Not sure. I have updated package.json in the repository to pin this library to 0.9.36. For those of you with this issue, simply change the line 

"@types/core-js": "~0.9.36",

to be

"@types/core-js": "0.9.36",
then run "npm rm @types/core-js"
and then "npm install" and the issue should be addressed.

DO NOT change your target to "es6". This will make your project break in many browsers. It's probably good in chrome, but for many other browsers, very little of es6 is supported.

**Comment by joeeames** [comment] 2017-03-16 08:33
Please review and verify the fix on your own environments.

**Closed as completed by joeeames** 2017-03-16 08:32 UTC

**Comment by dominikjeske** [comment] 2017-03-16 09:10
Unfortunatelly I still have errors - I have removed core-js and force 0.9.36 but after switch to es5 I have:

app/events/shared/event.service.ts(13,23): error TS2339: Property 'find' does not exist on type '{ id: number; name: string; date: string; time: string; price: number; imageUrl: string; location...'.
node_modules/@angular/common/src/directives/ng_class.d.ts(46,34): error TS2304: Cannot find name 'Set'.
node_modules/@angular/common/src/pipes/async_pipe.d.ts(44,38): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(369,30): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(415,30): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(416,20): error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(417,15): error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/compile_metadata.d.ts(418,246): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/directive_normalizer.d.ts(38,72): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/directive_normalizer.d.ts(40,74): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/metadata_resolver.d.ts(62,18): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/offline_compiler.d.ts(18,32): error TS2304: Cannot find name 'Map'.
node_modules/@angular/compiler/src/offline_compiler.d.ts(32,87): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/offline_compiler.d.ts(49,9): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/output/output_ast.d.ts(427,63): error TS2304: Cannot find name 'Set'.
node_modules/@angular/compiler/src/resource_loader.d.ts(13,23): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/runtime_compiler.d.ts(44,49): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/runtime_compiler.d.ts(46,65): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/util.d.ts(26,18): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/compiler/src/util.d.ts(27,46): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_init.d.ts(16,18): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(106,67): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(122,101): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(148,67): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/application_ref.d.ts(150,101): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(28,16): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(88,123): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/di/reflective_provider.d.ts(88,165): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Map'.
node_modules/@angular/core/src/facade/lang.d.ts(13,17): error TS2304: Cannot find name 'Set'.
node_modules/@angular/core/src/linker/compiler.d.ts(53,49): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/compiler.d.ts(61,65): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/ng_module_factory_loader.d.ts(14,34): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/linker/system_js_ng_module_factory_loader.d.ts(28,25): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/core/src/util/lang.d.ts(8,53): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/platform-browser-dynamic/src/resource_loader/resource_loader_impl.d.ts(10,23): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/platform-browser/src/browser/browser_adapter.d.ts(79,33): error TS2304: Cannot find name 'Map'.
node_modules/@angular/platform-browser/src/dom/dom_adapter.d.ts(97,42): error TS2304: Cannot find name 'Map'.
node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts(22,37): error TS2304: Cannot find name 'Map'.
node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.

npm ERR! Windows_NT 10.0.15058
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
npm ERR! Exit status 2

**Comment by joeeames** [comment] 2017-03-16 09:17
if a fresh clone and npm install works, (please verify that it does) then you've likely changed something while trying to fix this that has broken something. that or your removal of core js didn't work right. try deleting your node_modules directory and re-running npm install.

**Comment by dominikjeske** [comment] 2017-03-16 09:24
ok cleaning node_modules and revert changes in tsconfig.json fix the problem. Tnx for support.

**Comment by Levent0z** [comment] 2017-03-16 21:14
OK here's what fixed issues for me after I just rebased to #d5c8487:
1. rd node_packages /s
2. npm install
3. in tsconfig.json set target to es6 as suggested by bigdnf
4. in tsconfig.json replace the . in typeroots to .. as suggested by kahankel

**Comment by joeeames** [comment] 2017-03-16 21:45
@Levent0z those are definitely the wrong fixes. Review the issue to find the correct fix

**Comment by codiddle** [comment] 2017-03-18 14:33
Perfect clean build after doing exactly what Joe Eames suggested, except 1 tiny tweak:

> I have updated package.json in the repository to pin this library to 0.9.36. For those of you with this issue, simply change the line
> "@types/core-js": "~0.9.36",
> 
> to be
> 
> "@types/core-js": "0.9.36",
> then run "npm rm @types/core-js"
-- At this point I deleted all folders inside of angular_modules/ [which he also later suggested]
> and then "npm install" and the issue should be addressed.

I had made a change to the `typeRoots` configuration in `tsconfig.json` to target parent directory `../node_modules/@types/` while debugging a few days ago.  Reverting this to the original downloaded file path `./node_modules/@types/` [Where the folder actually lives lol] produced 0 errors, and I'm so very happy 👍

**Comment by krpmurugan** [comment] 2017-06-21 14:04
Any one can help me fix this below Error  while start the NPM

> ng2-fundamentals-demo@1.0.0 start C:\dev\ng2-fundamentals
> tsc && concurrently "npm run tsc:w" "npm run server"

 Error occured when executing command: npm run tsc:w
 Error: Unable to detect platform shell type. Please set SHELL_EXECUTE_FLAGS env variable.
     at detectExecuteFlags (C:\dev\ng2-fundamentals\node_modules\concurrently\node_modules\spawn-default-shell\src\get-shell.js:29:9)
     at getShell (C:\dev\ng2-fundamentals\node_modules\concurrently\node_modules\spawn-default-shell\src\get-shell.js:37:19)
     at Object.spawn (C:\dev\ng2-fundamentals\node_modules\concurrently\node_modules\spawn-default-shell\src\index.js:5:24)
     at C:\dev\ng2-fundamentals\node_modules\concurrently\src\main.js:195:34
     at arrayMap (C:\dev\ng2-fundamentals\node_modules\concurrently\node_modules\lodash\lodash.js:660:23)
     at Function.map (C:\dev\ng2-fundamentals\node_modules\concurrently\node_modules\lodash\lodash.js:9571:14)
     at run (C:\dev\ng2-fundamentals\node_modules\concurrently\src\main.js:181:22)
     at main (C:\dev\ng2-fundamentals\node_modules\concurrently\src\main.js:61:5)
     at Object.<anonymous> (C:\dev\ng2-fundamentals\node_modules\concurrently\src\main.js:424:1)
     at Module._compile (module.js:570:32)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\node\\nodejs\\node.exe" "C:\\Program Files\\node\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ng2-fundamentals-demo@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run server" `
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ng2-fundamentals-demo@1.0.0 start script 'tsc && concurrently "npm run tsc:w" "npm run server" '.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ng2-fundamentals-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm run tsc:w" "npm run server"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ng2-fundamentals-demo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ng2-fundamentals-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\dev\ng2-fundamentals\npm-debug.log

**Comment by BrianGLink** [comment] 2017-09-27 19:08
krpmurugan - please let me know if you've found a fix for this. I've read all the threads regarding this error and nothing has helped.

**Comment by joeeames** [comment] 2017-09-27 20:36
check out the course discussion forum. Fix for this is listed there.

**Comment by BrianGLink** [comment] 2017-09-27 20:40
Thanks, Joe - I did find a fix that worked which involved starting server.js directly from git-bash. Something in the script that barfs.

**Comment by LeebeeDev** [comment] 2017-10-10 12:33
krpmurugan - I'm facing the same issue. Help please

**Comment by krpmurugan** [comment] 2017-10-10 13:03
Hi,

I am uninstalled the node js and reinstalled the latest version and working
fine for me.


Regards,
R.Murugan

**Comment by philippfx** [comment] 2017-12-29 15:03
I have the same issue and for me running "npm start" from GitBash does not work, but running "npm start" from the Visual Studio Code Terminal works without any problems
